### PR TITLE
Fix #50 - stats parsing for haproxy

### LINKED ISSUE #50: Does not work for HAProxy 2.3.0
Plugin works fine for 2.2.4 but stopped working after upgrade to 2.3.0.

```
Check failed to run: undefined method `[]' for nil:NilClass, ["/opt/gems/sensu-plugins-haproxy/gems/sensu-plugins-haproxy-2.0.2/bin/check-haproxy.rb:226:in `block in acquire_services'", "/opt/gems/sensu-plugins-haproxy/gems/sensu-plugins-haproxy-2.0.2/bin/check-haproxy.rb:226:in `map'", "/opt/gems/sensu-plugins-haproxy/gems/sensu-plugins-haproxy-2.0.2/bin/check-haproxy.rb:226:in `acquire_services'", "/opt/gems/sensu-plugins-haproxy/gems/sensu-plugins-haproxy-2.0.2/bin/check-haproxy.rb:141:in `run'", "/opt/gems/sensu-plugins-haproxy/gems/sensu-plugin-4.0.0/lib/sensu-plugin/cli.rb:59:in `block in <class:CLI>'"]
```

### PR DESCRIPTION
**Pull request by ipiticas**
## Pull Request Checklist

Fixes #50.

**Is this in reference to an existing issue?**

#### General

- [x] Update Changelog following the conventions laid out on [Our CHANGELOG Guidelines ](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [x] Update README with any necessary configuration snippets

- [x] Binstubs are created if needed

- [x] RuboCop passes

- [x] Existing tests pass

#### New Plugins

- [x] Tests

- [x] Add the plugin to the README

- [x] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

### CODE REVIEW

**Review by majormoses — APPROVED** [review]
LGTM
