### ISSUE TITLE
Does not work for HAProxy 2.3.0

### ISSUE THREAD

**Issue by vooon** [sensu-plugins/sensu-plugins-haproxy#50]
Plugin works fine for 2.2.4 but stopped working after upgrade to 2.3.0.

```
Check failed to run: undefined method `[]' for nil:NilClass, ["/opt/gems/sensu-plugins-haproxy/gems/sensu-plugins-haproxy-2.0.2/bin/check-haproxy.rb:226:in `block in acquire_services'", "/opt/gems/sensu-plugins-haproxy/gems/sensu-plugins-haproxy-2.0.2/bin/check-haproxy.rb:226:in `map'", "/opt/gems/sensu-plugins-haproxy/gems/sensu-plugins-haproxy-2.0.2/bin/check-haproxy.rb:226:in `acquire_services'", "/opt/gems/sensu-plugins-haproxy/gems/sensu-plugins-haproxy-2.0.2/bin/check-haproxy.rb:141:in `run'", "/opt/gems/sensu-plugins-haproxy/gems/sensu-plugin-4.0.0/lib/sensu-plugin/cli.rb:59:in `block in <class:CLI>'"]
```

**Comment by vooon** [comment]
Found what were changed: header now have "-" element: 
```
...
"uweight", "-", "h2_headers_rcvd",
...
```

**Comment by majormoses** [comment]
Thanks for the submission, especially on such an old issue.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-haproxy/versions/2.0.3
