### PR TITLE
Fix stats parsing for haproxy 2.3

### LINKED ISSUE #50: Does not work for HAProxy 2.3.0
Plugin works fine for 2.2.4 but stopped working after upgrade to 2.3.0.

```
Check failed to run: undefined method `[]' for nil:NilClass, ["/opt/gems/sensu-plugins-haproxy/gems/sensu-plugins-haproxy-2.0.2/bin/check-haproxy.rb:226:in `block in acquire_services'", "/opt/gems/sensu-plugins-haproxy/gems/sensu-plugins-haproxy-2.0.2/bin/check-haproxy.rb:226:in `map'", "/opt/gems/sensu-plugins-haproxy/gems/sensu-plugins-haproxy-2.0.2/bin/check-haproxy.rb:226:in `acquire_services'", "/opt/gems/sensu-plugins-haproxy/gems/sensu-plugins-haproxy-2.0.2/bin/check-haproxy.rb:141:in `run'", "/opt/gems/sensu-plugins-haproxy/gems/sensu-plugin-4.0.0/lib/sensu-plugin/cli.rb:59:in `block in <class:CLI>'"]
```

### PR DESCRIPTION
**Pull request by vooon**
## Pull Request Checklist

Fixes #50.

#### General

- [x] Update Changelog following the conventions laid out on [Our CHANGELOG Guidelines ](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [x] Existing tests pass

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

### CODE REVIEW

**Review by ipiticas — APPROVED** [review]

**Review by ipiticas — APPROVED** [review]

File: bin/check-haproxy.rb [hunk 1]
```diff
@@ -223,7 +223,7 @@ def acquire_services #rubocop:disable all
     end
 
     parsed = CSV.parse(out, skip_blanks: true)
-    keys = parsed.shift.reject(&:nil?).map { |k| k.match(/(\w+)/)[0].to_sym }
+    keys = parsed.shift.reject(&:nil?).map { |k| k.match(/([\-\w]+)/)[0].to_sym }
```
Comment (majormoses) [inline bin/check-haproxy.rb:226]: From a backwards compatibility perspective I think we need to consider the `\-` optional if I understand correctly. Does that make sense? I have not spent much time with HAProxy lately so my knowledge may be out of date.
```suggestion
    keys = parsed.shift.reject(&:nil?).map { |k| k.match(/([(\-)?\w]+)/)[0].to_sym }
```

File: CHANGELOG.md [hunk 2]
```diff
@@ -6,6 +6,8 @@ Which is based on [Keep A Changelog](http://keepachangelog.com/)
 
 
 ## [Unreleased]
+### Fixed
```
Comment (majormoses) [inline CHANGELOG.md:9]:
```suggestion
### Added
```
I know this might sound a bit odd but I consider adding support for new versions of software to be enhancements as opposed to a fix. Really wish more projects would follow semver and bump major versions when they choose to change the behavior of the software in a way that breaks compatibility with previous expectations.

**Review by majormoses — CHANGES_REQUESTED** [review]
Thank you for reporting and submitting a patch. I do have one concern about backwards compatibility here and have suggested a change that I believe would make it safe to accept without a major version bump.

File: bin/check-haproxy.rb (hunk 1 above)
Comment (vooon) [reply bin/check-haproxy.rb:226]: Unfortunately i do not remember details, it's almost year old and i wrote golang replacement for it.

Comment (mdzidic) [reply bin/check-haproxy.rb:226]: Suggested change works fine with HAProxy v1.8.x and v2.4.x

**Comment by majormoses** [comment]
closing in favor of #54 and is released as https://rubygems.org/gems/sensu-plugins-haproxy/versions/2.0.3
